<a href="https://colab.research.google.com/github/Sandoval-Martinez-Jacquelin/Metodos-1/blob/main/Eliminaci%C3%B3n_gaussiana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **ELIMINACION GAUSSIANA**

In [11]:
import numpy as np
from numpy import array

from numpy import zeros

from math import *

In [12]:
#Ingreso del numero de incognitas y ecuaciones del sistema
n=4#int(input("Ingrese el numero de Incognitas y numero de ecuaciones= "))
#entradas=[] #Lista vacia para alamcenar las entradas de la matriz aumentada correspondiente al sistema de ecuaciones
entradas=[[1., -1., 2.,-1.,-8.], [2.,-2., 3.,-3.,-20.],[1.,1.,1.,0.,-2.], [1., -1., 4.,3.,4.]]#filas corrrespondientes al ejemplo

#ciclo iterativo para que el usuario ingrese las entradas de la matriz aumentada

#for k in range(n):
  #lista=[]
  #for d in range(n+1):
    #print("Ingrese el elemnto A",k,d,"de la matriz aumentada")
    #a=float(input(""))
    #lista.append(a)
  #entradas.append(lista)

matrix=array(entradas,dtype=float)#creacion de la matriz aumentada correspondiente al sistema de ecuaciones

print("La matriz aumentada que representa el sistema de ecuaciones es: \n",matrix)

La matriz aumentada que representa el sistema de ecuaciones es: 
 [[  1.  -1.   2.  -1.  -8.]
 [  2.  -2.   3.  -3. -20.]
 [  1.   1.   1.   0.  -2.]
 [  1.  -1.   4.   3.   4.]]


In [13]:
print("Las matrices equivalentes son: \n\n")
final=entradas
#Ciclo iterativo
#Eliminacion Gaussiana con sustitucion hacia atras

for i in range(n):

  entradas2=array(final)
  entradas=array(final)
  matrix=array(entradas2)


  col0=list(entradas2[: , i])#se obtiene la columna i del arreglo "entradas2"

  cero=[0.,0.,0.,0.]
  if col0 == cero:#si todas las entradas de la columna i son 0 ,el sistema no tiene solucion unica
    print("No existe solucion unica")
  else:
    col=col0[i:]#se obtienen los elemntos de la lista "col0" desde el subindice i hasta el ultimo elemnto y se guardan en la lista "col"

    for k in col:#ciclo para recorrer los elementos de la lista "col"
      if k!=0:
        a=k#el primer elemnto diferente de 0 ,de la lista "col" se guarda en la variable "a"
        break
    p=col.index(a)+i #se obtiene el subindice del valor de "a" ,dentro de la "col0" y se almacena en la variable "p"

    if p!=i:#si el valor de p e i son distintos,se intercambian las filas p e i del arreglo "entradas2"
      b=entradas[i]
      c=entradas[p]
      entradas2[i]=c
      entradas2[p]=b





    final=[]#lista vacia para guardar las filas de la matrices equivbalentes resultantes de las operaciones elemntales
    for k in range(i+1):#ciclo para agregar a la lista vacia las fila 0,1,...,i del arreglo "entradas2"
      final.append(entradas2[k])

    for j in range(i+1,n):#ciclo iterativo para el calculo de los valores de m

      m=-entradas2[j][i]/entradas2[i][i]


      fila1=[]#creacion de una lista vacia
      for f in entradas2[i]:#ciclo iterativo para guardar los valoes resultantes del producto de m con cada elemnto de la fila i del arreglo "entradas2"
         fila1.append(f*m)


      sum=list(array(fila1)+array(entradas2[j]))#creacion de una lista que alamacena la nueva fila j del arreglo "entradas2"
      final.append(sum)#se agrega la nueva fila j del arreglo "entradas2 " a la lista "final"
  print("La Matriz equivalente es: \n",array(final))#se imprime la matriz equivalente ,resultado de las operaciones elemntales


Las matrices equivalentes son: 


La Matriz equivalente es: 
 [[ 1. -1.  2. -1. -8.]
 [ 0.  0. -1. -1. -4.]
 [ 0.  2. -1.  1.  6.]
 [ 0.  0.  2.  4. 12.]]
La Matriz equivalente es: 
 [[ 1. -1.  2. -1. -8.]
 [ 0.  2. -1.  1.  6.]
 [ 0.  0. -1. -1. -4.]
 [ 0.  0.  2.  4. 12.]]
La Matriz equivalente es: 
 [[ 1. -1.  2. -1. -8.]
 [ 0.  2. -1.  1.  6.]
 [ 0.  0. -1. -1. -4.]
 [ 0.  0.  0.  2.  4.]]
La Matriz equivalente es: 
 [[ 1. -1.  2. -1. -8.]
 [ 0.  2. -1.  1.  6.]
 [ 0.  0. -1. -1. -4.]
 [ 0.  0.  0.  2.  4.]]


In [14]:
soluciones=zeros(n,dtype=float)#creacion de un arreglo inicializado en 0 para guardar las soluciones del sistema
soluciones[n-1]=final[n-1][n]/final[n-1][n-1]#calculo de Xn


def sumatoria(i):#funcion para el calculo de la sumatoria que esta dentro de la formula de Xi
  s=0
  for j in range(i+1,n):
    s+=final[i][j]*soluciones[j]
  return s



for i in range(n-2,-1,-1):#ciclo iterativo para el calculo de las soluciones Xi
  soluciones[i]=(final[i][n]-sumatoria(i))/final[i][i]


print("Las soluciones del sistema son : \n")

for k in range(n):#ciclo iterativo para la impresion de las soluciones
  print("X",k+1,"=",soluciones[k])

Las soluciones del sistema son : 

X 1 = -7.0
X 2 = 3.0
X 3 = 2.0
X 4 = 2.0
