<a href="https://colab.research.google.com/github/Sandoval-Martinez-Jacquelin/Metodos-1/blob/main/Eliminaci%C3%B3n_gaussiana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **ELIMINACION GAUSSIANA**

In [40]:
import numpy as np
from numpy import array

from numpy import zeros

from math import *

In [41]:

n=4#int(input("Ingrese el numero de Incognitas y numero de ecuaciones= "))
entradas=[[1., -1., 2.,-1.,-8.], [2.,-2., 3.,-3.,-20.],[1.,1.,1.,0.,-2.], [1., -1., 4.,3.,4.]]#[]
#for k in range(n):
  #lista=[]
  #for d in range(n+1):
    #print("Ingrese el elemnto A",k,d,"de la matriz aumentada")
    #a=float(input(""))
    #lista.append(a)
  #entradas.append(lista)

matrix=array(entradas,dtype=float)

print("La matriz aumentada que representa el sistema de ecuaciones es: \n",matrix)

La matriz aumentada que representa el sistema de ecuaciones es: 
 [[  1.  -1.   2.  -1.  -8.]
 [  2.  -2.   3.  -3. -20.]
 [  1.   1.   1.   0.  -2.]
 [  1.  -1.   4.   3.   4.]]


In [42]:
final=entradas
for i in range(n):

  entradas2=array(final)
  entradas=array(final)
  matrix=array(entradas2)


  fila0=list(entradas2[: , i])

  cero=[0.,0.,0.,0.]
  if fila0 == cero:
    print("No existe solucion unica")
  else:
    co=fila0[i:]

    for k in co:
      if k!=0:
        a=k
        break
    p=co.index(a)+i

    if p!=i:
      b=entradas[i]
      c=entradas[p]
      entradas2[i]=c
      entradas2[p]=b





    final=[]
    for k in range(i+1):
      final.append(entradas2[k])

    for j in range(i+1,n):

      m=-entradas2[j][i]/entradas2[i][i]


      fila1=[]
      for f in entradas2[i]:
         fila1.append(f*m)


      sum=list(array(fila1)+array(entradas2[j]))
      final.append(sum)
  print("La Matriz equivalente es: \n",array(final))


La Matriz equivalente es: 
 [[ 1. -1.  2. -1. -8.]
 [ 0.  0. -1. -1. -4.]
 [ 0.  2. -1.  1.  6.]
 [ 0.  0.  2.  4. 12.]]
La Matriz equivalente es: 
 [[ 1. -1.  2. -1. -8.]
 [ 0.  2. -1.  1.  6.]
 [ 0.  0. -1. -1. -4.]
 [ 0.  0.  2.  4. 12.]]
La Matriz equivalente es: 
 [[ 1. -1.  2. -1. -8.]
 [ 0.  2. -1.  1.  6.]
 [ 0.  0. -1. -1. -4.]
 [ 0.  0.  0.  2.  4.]]
La Matriz equivalente es: 
 [[ 1. -1.  2. -1. -8.]
 [ 0.  2. -1.  1.  6.]
 [ 0.  0. -1. -1. -4.]
 [ 0.  0.  0.  2.  4.]]


In [45]:
soluciones=zeros(n,dtype=float)
soluciones[n-1]=final[n-1][n]/final[n-1][n-1]


def sumatoria(i):
  s=0
  for j in range(i+1,n):
    s+=final[i][j]*soluciones[j]
  return s



for i in range(n-2,-1,-1):
  soluciones[i]=(final[i][n]-sumatoria(i))/final[i][i]
print("Las soluciones del sistema son: ",soluciones)

print("Las soluciones del sistema son : ")

for k in range(n):
  print("X",k+1,"=",soluciones[k])

Las soluciones del sistema son:  [-7.  3.  2.  2.]
Las soluciones del sistema son : 
X 1 = -7.0
X 2 = 3.0
X 3 = 2.0
X 4 = 2.0
