<a href="https://colab.research.google.com/github/Sandoval-Martinez-Jacquelin/Metodos-1/blob/main/Eliminaci%C3%B3n_gaussiana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **ELIMINACION GAUSSIANA**

In [1042]:
import numpy as np
from numpy import array

from numpy import zeros
from tabulate import tabulate
from math import *

In [1043]:

n=4#int(input("Ingrese el numero de Incognitas y numero de ecuaciones= "))
entradas=[[1., -1., 2.,-1.,-8.], [2.,-2., 3.,-3.,-20.],[1.,1.,1.,0.,-2.], [1., -1., 4.,3.,4.]]#[]
#for k in range(n):
  #lista=[]
  #for d in range(n+1):
    #print("Ingrese el elemnto A",k,d,"de la matriz aumentada")
    #a=int(input(""))
    #lista.append(a)
  #entradas.append(lista)
print(entradas)
matrix=array(entradas,dtype=float)

print(matrix)

[[1.0, -1.0, 2.0, -1.0, -8.0], [2.0, -2.0, 3.0, -3.0, -20.0], [1.0, 1.0, 1.0, 0.0, -2.0], [1.0, -1.0, 4.0, 3.0, 4.0]]
[[  1.  -1.   2.  -1.  -8.]
 [  2.  -2.   3.  -3. -20.]
 [  1.   1.   1.   0.  -2.]
 [  1.  -1.   4.   3.   4.]]


In [1044]:
entradas2=[]
for k in entradas:
  entradas2.append(k)


In [1045]:
for i in range(n):

  entradas2=array(final)
  entradas=array(final)
  matrix=array(entradas2)


  fila0=list(entradas2[: , i])

  cero=[0.,0.,0.,0.]
  if fila0 == cero:
    print("no existe solucion unica")
  else:
    co=fila0[i:]

    for k in co:
      if k!=0:
        a=k
        break
    p=co.index(a)+i

    if p!=i:
      b=entradas[i]
      c=entradas[p]
      entradas2[i]=c
      entradas2[p]=b




    co=[]
    final=[]
    for k in range(i+1):
      final.append(entradas2[k])

    for j in range(i+1,n):

      m=-entradas2[j][i]/entradas2[i][i]
      co.append(m)

      fila1=[]
      for f in entradas2[i]:
         fila1.append(f*m)


      sum=list(array(fila1)+array(entradas2[j]))
      final.append(sum)
  print("final\n",array(final))


final
 [[ 1. -1.  2. -1. -8.]
 [ 0.  1. -1.  1.  6.]
 [ 0.  0.  1. -1. -4.]
 [ 0.  0.  0.  1. 20.]]
final
 [[ 1. -1.  2. -1. -8.]
 [ 0.  1. -1.  1.  6.]
 [ 0.  0.  1. -1. -4.]
 [ 0.  0.  0.  1. 20.]]
final
 [[ 1. -1.  2. -1. -8.]
 [ 0.  1. -1.  1.  6.]
 [ 0.  0.  1. -1. -4.]
 [ 0.  0.  0.  1. 20.]]
final
 [[ 1. -1.  2. -1. -8.]
 [ 0.  1. -1.  1.  6.]
 [ 0.  0.  1. -1. -4.]
 [ 0.  0.  0.  1. 20.]]


In [1003]:
#entradas2=final
print(entradas2,"e2")
i=0
fila0=list(matrix[: , i])
print(fila0)
cero=[0.,0.,0.,0.]
if fila0 == cero:
  print("no existe solucion unica")
else:
  co=[]
  for k in fila0:
    if k!=0:
      a=k
      break
  p=fila0.index(a)
  print(a,p,i)
  if p!=i:
    b=entradas[i]
    c=entradas[p]
    entradas2[i]=c
    entradas2[p]=b

  print(entradas2,"e2")
  entradas2[i][i]=entradas2[i][i]/entradas2[i][i]
  co=[]
  final=[]
  for k in range(i+1):
    final.append(entradas2[k])
  for j in range(i+1,n):

    m=-entradas2[j][i]/entradas2[i][i]
    co.append(m)

    fila1=[]
    for f in entradas2[i]:
       fila1.append(f*m)

    print(array(fila1),"fila1")
    sum=list(array(fila1)+array(entradas2[j]))
    final.append(sum)
  print("final\n",array(final))





[[1.0, -1.0, 2.0, -1.0, -8.0], [2.0, -2.0, 3.0, -3.0, -20.0], [1.0, 1.0, 1.0, 0.0, -2.0], [1.0, -1.0, 4.0, 3.0, 4.0]] e2
[1.0, 2.0, 1.0, 1.0]
1.0 0 0
[[1.0, -1.0, 2.0, -1.0, -8.0], [2.0, -2.0, 3.0, -3.0, -20.0], [1.0, 1.0, 1.0, 0.0, -2.0], [1.0, -1.0, 4.0, 3.0, 4.0]] e2
[-2.  2. -4.  2. 16.] fila1
[-1.  1. -2.  1.  8.] fila1
[-1.  1. -2.  1.  8.] fila1
final
 [[ 1. -1.  2. -1. -8.]
 [ 0.  0. -1. -1. -4.]
 [ 0.  2. -1.  1.  6.]
 [ 0.  0.  2.  4. 12.]]


In [1004]:
i=1
entradas2=array(final)
entradas=array(final)
matrix=array(entradas2)
print(entradas2,"e2final")

fila0=list(entradas2[: , i])
print(fila0,"f0")
cero=[0.,0.,0.,0.]
if fila0 == cero:
  print("no existe solucion unica")
else:
  co=[]
  for k in fila0[i:]:
    if k!=0:
      a=k
      break
  p=fila0.index(a)
  print(a,p,i)
  if p!=i:
    b=entradas[i]
    c=entradas[p]
    entradas2[i]=c
    entradas2[p]=b

  print(entradas2,"eee2")
  entradas2[i][i]=entradas2[i][i]/entradas2[i][i]
  co=[]
  final=[]
  for k in range(i+1):
    final.append(entradas2[k])

  for j in range(i+1,n):

    m=-entradas2[j][i]/entradas2[i][i]
    co.append(m)

    fila1=[]
    for f in entradas2[i]:
       fila1.append(f*m)

    print(array(fila1),"fila1")
    sum=list(array(fila1)+array(entradas2[j]))
    final.append(sum)
  print("final\n",array(final))


i=1
entradas2=array(final)
entradas=array(final)
matrix=array(entradas2)
print(entradas2,"e2final")

fila0=list(entradas2[: , i])
print(fila0,"f0")
cero=[0.,0.,0.,0.]
if fila0 == cero:
  print("no existe solucion unica")
else:
  co=[]
  for k in fila0[i:]:
    if k!=0:
      a=k
      break
  p=fila0.index(a)
  print(a,p,i)
  if p!=i:
    b=entradas[i]
    c=entradas[p]
    entradas2[i]=c
    entradas2[p]=b

  print(entradas2,"eee2")
  entradas2[i][i]=entradas2[i][i]/entradas2[i][i]
  co=[]
  final=[]
  for k in range(i+1):
    final.append(entradas2[k])

  for j in range(i+1,n):

    m=-entradas2[j][i]/entradas2[i][i]
    co.append(m)

    fila1=[]
    for f in entradas2[i]:
       fila1.append(f*m)

    print(array(fila1),"fila1")
    sum=list(array(fila1)+array(entradas2[j]))
    final.append(sum)
  print("final\n",array(final))


[[ 1. -1.  2. -1. -8.]
 [ 0.  0. -1. -1. -4.]
 [ 0.  2. -1.  1.  6.]
 [ 0.  0.  2.  4. 12.]] e2final
[-1.0, 0.0, 2.0, 0.0] f0
2.0 2 1
[[ 1. -1.  2. -1. -8.]
 [ 0.  2. -1.  1.  6.]
 [ 0.  0. -1. -1. -4.]
 [ 0.  0.  2.  4. 12.]] eee2
[-0. -0.  0. -0. -0.] fila1
[-0. -0.  0. -0. -0.] fila1
final
 [[ 1. -1.  2. -1. -8.]
 [ 0.  1. -1.  1.  6.]
 [ 0.  0. -1. -1. -4.]
 [ 0.  0.  2.  4. 12.]]
[[ 1. -1.  2. -1. -8.]
 [ 0.  1. -1.  1.  6.]
 [ 0.  0. -1. -1. -4.]
 [ 0.  0.  2.  4. 12.]] e2final
[-1.0, 1.0, 0.0, 0.0] f0
1.0 1 1
[[ 1. -1.  2. -1. -8.]
 [ 0.  1. -1.  1.  6.]
 [ 0.  0. -1. -1. -4.]
 [ 0.  0.  2.  4. 12.]] eee2
[-0. -0.  0. -0. -0.] fila1
[-0. -0.  0. -0. -0.] fila1
final
 [[ 1. -1.  2. -1. -8.]
 [ 0.  1. -1.  1.  6.]
 [ 0.  0. -1. -1. -4.]
 [ 0.  0.  2.  4. 12.]]


In [1005]:
i=2
entradas2=array(final)
entradas=array(final)
matrix=array(entradas2)
print(entradas2,"e2final")

fila0=list(entradas2[: , i])
print(fila0,"f0")
cero=[0.,0.,0.,0.]
if fila0 == cero:
  print("no existe solucion unica")
else:
  co=fila0[i:]
  print("co",co)
  for k in co:
    if k!=0:
      a=k
      break
  p=co.index(a)+i
  print(a,p,i)
  if p!=i:
    b=entradas[i]
    c=entradas[p]
    entradas2[i]=c
    entradas2[p]=b


  print(entradas2,"eee2")
  entradas2[i][i]=entradas2[i][i]/entradas2[i][i]
  co=[]
  final=[]
  for k in range(i+1):
    final.append(entradas2[k])

  for j in range(i+1,n):

    m=-entradas2[j][i]/entradas2[i][i]
    co.append(m)

    fila1=[]
    for f in entradas2[i]:
       fila1.append(f*m)

    print(array(fila1),"fila1")
    sum=list(array(fila1)+array(entradas2[j]))
    final.append(sum)
  print("final\n",array(final))


[[ 1. -1.  2. -1. -8.]
 [ 0.  1. -1.  1.  6.]
 [ 0.  0. -1. -1. -4.]
 [ 0.  0.  2.  4. 12.]] e2final
[2.0, -1.0, -1.0, 2.0] f0
co [-1.0, 2.0]
-1.0 2 2
[[ 1. -1.  2. -1. -8.]
 [ 0.  1. -1.  1.  6.]
 [ 0.  0. -1. -1. -4.]
 [ 0.  0.  2.  4. 12.]] eee2
[-0. -0. -2.  2.  8.] fila1
final
 [[ 1. -1.  2. -1. -8.]
 [ 0.  1. -1.  1.  6.]
 [ 0.  0.  1. -1. -4.]
 [ 0.  0.  0.  6. 20.]]


In [1006]:
i=3
entradas2=array(final)
entradas=array(final)
matrix=array(entradas2)
print(entradas2,"e2final")

fila0=list(entradas2[: , i])
print(fila0,"f0")
cero=[0.,0.,0.,0.]
if fila0 == cero:
  print("no existe solucion unica")
else:
  co=fila0[i:]
  print("co",co)
  for k in co:
    if k!=0:
      a=k
      break
  p=fila0.index(a)
  print(a,p,i)
  if p!=i:
    b=entradas[i]
    c=entradas[p]
    entradas2[i]=c
    entradas2[p]=b


  print(entradas2,"eee2")
  entradas2[i][i]=entradas2[i][i]/entradas2[i][i]
  co=[]
  final=[]
  for k in range(i+1):
    final.append(entradas2[k])

  for j in range(i+1,n):

    m=-entradas2[j][i]/entradas2[i][i]
    co.append(m)

    fila1=[]
    for f in entradas2[i]:
       fila1.append(f*m)

    print(array(fila1),"fila1")
    sum=list(array(fila1)+array(entradas2[j]))
    final.append(sum)
  print("final\n",array(final))


[[ 1. -1.  2. -1. -8.]
 [ 0.  1. -1.  1.  6.]
 [ 0.  0.  1. -1. -4.]
 [ 0.  0.  0.  6. 20.]] e2final
[-1.0, 1.0, -1.0, 6.0] f0
co [6.0]
6.0 3 3
[[ 1. -1.  2. -1. -8.]
 [ 0.  1. -1.  1.  6.]
 [ 0.  0.  1. -1. -4.]
 [ 0.  0.  0.  6. 20.]] eee2
final
 [[ 1. -1.  2. -1. -8.]
 [ 0.  1. -1.  1.  6.]
 [ 0.  0.  1. -1. -4.]
 [ 0.  0.  0.  1. 20.]]
