<a href="https://colab.research.google.com/github/Sandoval-Martinez-Jacquelin/Metodos-1/blob/main/Eliminaci%C3%B3n_gaussiana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **ELIMINACION GAUSSIANA**

In [545]:
import numpy as np
from numpy import array

from numpy import zeros
from tabulate import tabulate
from math import *

In [546]:

n=4#int(input("Ingrese el numero de Incognitas y numero de ecuaciones= "))
entradas=[[0., -1., 2.,-1.,-8.], [2.,-2., 3.,-3.,-20.],[10.,1.,1.,0.,-2.], [20., -1., 4.,3.,4.]]#[]
#for k in range(n):
  #lista=[]
  #for d in range(n+1):
    #print("Ingrese el elemnto A",k,d,"de la matriz aumentada")
    #a=int(input(""))
    #lista.append(a)
  #entradas.append(lista)
print(entradas)
matrix=array(entradas,dtype=float)

print(matrix)

[[0.0, -1.0, 2.0, -1.0, -8.0], [2.0, -2.0, 3.0, -3.0, -20.0], [10.0, 1.0, 1.0, 0.0, -2.0], [20.0, -1.0, 4.0, 3.0, 4.0]]
[[  0.  -1.   2.  -1.  -8.]
 [  2.  -2.   3.  -3. -20.]
 [ 10.   1.   1.   0.  -2.]
 [ 20.  -1.   4.   3.   4.]]


In [547]:
print(entradas[0][1])

-1.0


In [548]:
entradas2=[]
for k in entradas:
  entradas2.append(k)


In [549]:
entradas2=entradas
i=0
fila0=list(matrix[: , 0])
print(fila0)
cero=[0.,0.,0.,0.]
if fila0 == cero:
  print("no existe solucion unica")
else:
  co=[]
  for k in fila0:
    if k!=0:
      a=k
      break
  p=fila0.index(a)
  print(a,p,i)
  if p!=i:
    b=entradas[i]
    c=entradas[p]
    entradas2[i]=c
    entradas2[p]=b

  print(entradas2)
  co=[]
  for j in range(i+1,n):

    m=-entradas2[j][i]/entradas2[i][i]
    co.append(m)

    fila1=[]
    for f in entradas2[i]:
       fila1.append(f*m)
    print(fila1,"fila1")



  print(co)
  print(entradas2,"e2")






[0.0, 2.0, 10.0, 20.0]
2.0 1 0
[[2.0, -2.0, 3.0, -3.0, -20.0], [0.0, -1.0, 2.0, -1.0, -8.0], [10.0, 1.0, 1.0, 0.0, -2.0], [20.0, -1.0, 4.0, 3.0, 4.0]]
[-0.0, 0.0, -0.0, 0.0, 0.0] fila1
[-10.0, 10.0, -15.0, 15.0, 100.0] fila1
[-20.0, 20.0, -30.0, 30.0, 200.0] fila1
[-0.0, -5.0, -10.0]
[[2.0, -2.0, 3.0, -3.0, -20.0], [0.0, -1.0, 2.0, -1.0, -8.0], [0.0, 1.0, 1.0, 0.0, -2.0], [0.0, -1.0, 4.0, 3.0, 4.0]] e2
