<a href="https://colab.research.google.com/github/Sandoval-Martinez-Jacquelin/Metodos-1/blob/main/Eliminaci%C3%B3n_gaussiana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **ELIMINACION GAUSSIANA**

In [9]:
import numpy as np
from numpy import array

from numpy import zeros
from tabulate import tabulate
from math import *

In [10]:

n=4#int(input("Ingrese el numero de Incognitas y numero de ecuaciones= "))
entradas=[[1., -1., 2.,-1.,-8.], [2.,-2., 3.,-3.,-20.],[1.,1.,1.,0.,-2.], [1., -1., 4.,3.,4.]]#[]
#for k in range(n):
  #lista=[]
  #for d in range(n+1):
    #print("Ingrese el elemnto A",k,d,"de la matriz aumentada")
    #a=int(input(""))
    #lista.append(a)
  #entradas.append(lista)
print(entradas)
matrix=array(entradas,dtype=float)

print(matrix)

[[1.0, -1.0, 2.0, -1.0, -8.0], [2.0, -2.0, 3.0, -3.0, -20.0], [1.0, 1.0, 1.0, 0.0, -2.0], [1.0, -1.0, 4.0, 3.0, 4.0]]
[[  1.  -1.   2.  -1.  -8.]
 [  2.  -2.   3.  -3. -20.]
 [  1.   1.   1.   0.  -2.]
 [  1.  -1.   4.   3.   4.]]


In [11]:
entradas2=[]
for k in entradas:
  entradas2.append(k)


In [12]:
final=entradas
for i in range(n):

  entradas2=array(final)
  entradas=array(final)
  matrix=array(entradas2)


  fila0=list(entradas2[: , i])

  cero=[0.,0.,0.,0.]
  if fila0 == cero:
    print("no existe solucion unica")
  else:
    co=fila0[i:]

    for k in co:
      if k!=0:
        a=k
        break
    p=co.index(a)+i

    if p!=i:
      b=entradas[i]
      c=entradas[p]
      entradas2[i]=c
      entradas2[p]=b




    co=[]
    final=[]
    for k in range(i+1):
      final.append(entradas2[k])

    for j in range(i+1,n):

      m=-entradas2[j][i]/entradas2[i][i]
      co.append(m)

      fila1=[]
      for f in entradas2[i]:
         fila1.append(f*m)


      sum=list(array(fila1)+array(entradas2[j]))
      final.append(sum)
  print("final\n",array(final))


final
 [[ 1. -1.  2. -1. -8.]
 [ 0.  0. -1. -1. -4.]
 [ 0.  2. -1.  1.  6.]
 [ 0.  0.  2.  4. 12.]]
final
 [[ 1. -1.  2. -1. -8.]
 [ 0.  2. -1.  1.  6.]
 [ 0.  0. -1. -1. -4.]
 [ 0.  0.  2.  4. 12.]]
final
 [[ 1. -1.  2. -1. -8.]
 [ 0.  2. -1.  1.  6.]
 [ 0.  0. -1. -1. -4.]
 [ 0.  0.  0.  2.  4.]]
final
 [[ 1. -1.  2. -1. -8.]
 [ 0.  2. -1.  1.  6.]
 [ 0.  0. -1. -1. -4.]
 [ 0.  0.  0.  2.  4.]]
