<a href="https://colab.research.google.com/github/Sandoval-Martinez-Jacquelin/Metodos-1/blob/main/F.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**FACTORIZACION LU**

In [1]:
import numpy as np
from numpy import array

from numpy import zeros

from math import *

In [2]:
n=4#int(input("Ingrese la dimension n= "))

matriz=array([[1.0, 1.0, 0.0, 3.0], [2.0, 1.0, -1.0, 1.0], [3.0, -1.0, -1.0, 2.0], [-1.0, 2.0, 3.0, -1.0]])#Ingreso de la matriz A para el ejemplo
#matriz=zeros((n, n)) #matriz A inicializada en 0
#for i in range(n): #ciclo iterativo para ingresar las entradas aij de la matriz A
  #for j in range(n):
    #print("Ingrese la entrada ",i+1,j+1,"de la matriz A")
    #a=float(input(""))
    #matriz[i][j]=a


diagonal_L=[1.0, 1.0, 1.0, 1.0]#se definen las entradas de la diagonal de la matriz L
diagonal_U=[1.0, -1.0, 3.0, -13.0]#se definen las entradas de la diagonal de la matriz U

#for i in range(n): #ciclo iterativo para ingresar las entradas de la diagonal de la matriz L
  #print("Ingrese la entrada ",i,i," de la diagonal de L")
  #l=float(input(""))
  #diagonal_L.append(l)


#for i in range(n): #ciclo iterativo para ingresar las entradas de la diagonal de la matriz U
  #print("Ingrese la entrada ",i,i," de la diagonal de U")
  #u=float(input(""))
  #diagonal_U.append(u)
print("La matriz A es ")
print(matriz)

La matriz A es 
[[ 1.  1.  0.  3.]
 [ 2.  1. -1.  1.]
 [ 3. -1. -1.  2.]
 [-1.  2.  3. -1.]]


In [3]:
matriz_L= zeros((n, n))#se crea la matriz L incializada en 0
matriz_U=zeros((n,n))#se crea la matriz U incializada en 0
for k in range(n):#cilo iterativo para agregar a la matriz L y a la matriz U las entradas de sus diagonales
  matriz_L[k][k]=diagonal_L[k]
  matriz_U[k][k]=diagonal_U[k]



In [4]:
def sumatoria1(i,j):#se define una funcion para realizar el cálculo de la sumatoria que esta dentro de la formula del cálculo de uij
  s=0
  for k in range(i):
    s+=matriz_L[i][k]*matriz_U[k][j]
  return s

def sumatoria2(i,j):#se define una funcion para realizar el cálculo de la sumatoria que esta dentro de la formula del cálculo de lji
  s=0
  for k in range(i):
    s+=matriz_L[j][k]*matriz_U[k][i]
  return s


In [5]:
a_11=diagonal_L[0]*diagonal_U[0]#Cálculo de a11

#Algoritmo factorizacion LU

if a_11==0:#si la entrada a11=0 ,la factorizacion es imposible
  print("Factorizacion imposible ")

else:
  for j in range(n):#Ciclo iterativo para el cálculo de la primera fila de U y de la primera columna de L
    u1j=matriz[0][j]/diagonal_L[0]#cálculo de la entrada 1j de la matriz U
    matriz_U[0][j]=u1j#se añade a la matriz U su primera fila

    lj1=matriz[j][0]/diagonal_U[0]#cálculo de la entrada j1 de la matriz L
    matriz_L[j][0]=lj1#se añade a la matriz L su primera columna


  for i in range(1,n-1):#ciclo para realizar el cálculo de lii*uii
    p=diagonal_L[i]*diagonal_U[i]#cálculo de lii*uii

    if p==0:#si lii*uii=0 la factorizacion es imposible
      print("Factorizacion imposible")
      break
    for j in range(i+1,n):#ciclo iterativo para el cálculo de la i-esima fila de U y de la j-esima columna de L
      matriz_U[i][j]=(1/matriz_L[i][i])*(matriz[i][j]-sumatoria1(i,j))#cálculo de la entrada uij de la matriz U
      matriz_L[j][i]=(1/matriz_U[i][i])*(matriz[j][i]-sumatoria2(i,j))#cálculo de la entrada lji de la matriz L





In [6]:
for i in range(n):#ciclo iterativo para imprimir las entradas lij y uij de las matrices U y L para j=1,..,n e i=1,..,n
  for j in range(i+1):
    print("La entrada ",i+1,j+1,"de la matriz L es ",matriz_L[i][j])
print("\n")
for i in range(n):
  for j in range(i+1):
    print("La entrada ",i+1,j+1,"de la matriz U es ",matriz_U[i][j])



La entrada  1 1 de la matriz L es  1.0
La entrada  2 1 de la matriz L es  2.0
La entrada  2 2 de la matriz L es  1.0
La entrada  3 1 de la matriz L es  3.0
La entrada  3 2 de la matriz L es  4.0
La entrada  3 3 de la matriz L es  1.0
La entrada  4 1 de la matriz L es  -1.0
La entrada  4 2 de la matriz L es  -3.0
La entrada  4 3 de la matriz L es  0.0
La entrada  4 4 de la matriz L es  1.0


La entrada  1 1 de la matriz U es  1.0
La entrada  2 1 de la matriz U es  0.0
La entrada  2 2 de la matriz U es  -1.0
La entrada  3 1 de la matriz U es  0.0
La entrada  3 2 de la matriz U es  0.0
La entrada  3 3 de la matriz U es  3.0
La entrada  4 1 de la matriz U es  0.0
La entrada  4 2 de la matriz U es  0.0
La entrada  4 3 de la matriz U es  0.0
La entrada  4 4 de la matriz U es  -13.0


In [7]:
if matriz_U[n-1][n-1]*matriz_L[n-1][n-1]==0:#si la entrada lnn*unn=ann es 0 ,la matriz A es singular
  print("A=LU,pero A es singular")

#Se imprimen las matrices A,L y U
print("La matriz A=LU es ")
print(matriz)
print("\n La matriz L es=")
print(matriz_L)
print("\n La matriz U es =")
print(matriz_U)


La matriz A=LU es 
[[ 1.  1.  0.  3.]
 [ 2.  1. -1.  1.]
 [ 3. -1. -1.  2.]
 [-1.  2.  3. -1.]]

 La matriz L es=
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 3.  4.  1.  0.]
 [-1. -3.  0.  1.]]

 La matriz U es =
[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]
