<a href="https://colab.research.google.com/github/Sandoval-Martinez-Jacquelin/Metodos-1/blob/main/Factorizacion_LU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**FACTORIZACION LU**

In [110]:
import numpy as np
from numpy import array

from numpy import zeros

from math import *

In [111]:
n=4#int(input("Ingrese la dimension n= "))
#filas=[]
matriz=array([[1.0, 1.0, 0.0, 3.0], [2.0, 1.0, -1.0, 1.0], [3.0, -1.0, -1.0, 2.0], [-1.0, 2.0, 3.0, -1.0]])#[]
#for i in range(n):
  #for j in range(n):
    #print("Ingrese la entrada ",i,j)
    #a=float(input(""))
    #filas.append(a)
  #matriz.append(filas)
  #filas=[]

diagonal_L=[1.0, 1.0, 1.0, 1.0]#[]
diagonal_U=[1.0, -1.0, 3.0, -13.0]#[]

#for i in range(n):
  #print("Ingrese la entrada ",i,i," de la diagonal de L")
  #l=float(input(""))
  #diagonal_L.append(l)


#for i in range(n):
  #print("Ingrese la entrada ",i,i," de la diagonal de U")
  #u=float(input(""))
  #diagonal_U.append(u)


In [112]:
matriz_L= zeros((n, n))
matriz_U=zeros((n,n))
for k in range(n):
  matriz_L[k][k]=diagonal_L[k]
  matriz_U[k][k]=diagonal_U[k]

print(matriz_U)
print(matriz_L)

[[  1.   0.   0.   0.]
 [  0.  -1.   0.   0.]
 [  0.   0.   3.   0.]
 [  0.   0.   0. -13.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [113]:
def sumatoria1(i,j):
  s=0
  for k in range(i):
    s+=matriz_L[i][k]*matriz_U[k][j]
  return s

def sumatoria2(i,j):
  s=0
  for k in range(i):
    s+=matriz_L[j][k]*matriz_U[k][i]
  return s


In [114]:
a_11=diagonal_L[0]*diagonal_U[0]#Calculo de a11



#Algoritmo factorizacion LU
if a_11==0:
  print("Factorizacion simple ")

else:
  for j in range(n):#Ciclo iterativo para el calculo de la primera fila de U y de la primera columna de L
    u1j=matriz[0][j]/diagonal_L[0]#calculo de la entrada 1j de la matriz U
    matriz_U[0][j]=u1j#se añade la primera fila de la matriz u

    lj1=matriz[j][0]/diagonal_U[0]#calculo de la entrada j1 de la matriz L
    matriz_L[j][0]=lj1#se añade la primera columna de la matriz L


  fila_L=[]
  fila_U=[]

  for i in range(1,n-1):#ciclo para realizar el calculo de lii*uii
    p=diagonal_L[i]*diagonal_U[i]

    if p==0:#si lii*uii=0 la factorizacion es imposible
      print("Factorizacion imposible")
      break
    for j in range(i+1,n):
      matriz_U[i][j]=(1/matriz_L[i][i])*(matriz[i][j]-sumatoria1(i,j))
      matriz_L[j][i]=(1/matriz_U[i][i])*(matriz[j][i]-sumatoria2(i,j))





In [ ]:
if matriz_U[n][n]*matriz