<a href="https://colab.research.google.com/github/Sandoval-Martinez-Jacquelin/Metodos-1/blob/main/Pivoteo%20Parcial%20Escalonado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PIVOTEO PARCIAL ESCALONADO**

In [58]:
import numpy as np
from numpy import array

from numpy import zeros

from math import *

In [59]:
#Ingreso del numero de incognitas y ecuaciones del sistema
n=3#int(input("Ingrese el numero de Incognitas y numero de ecuaciones= "))
#entradas=[] #Lista vacia para alamcenar las filas de la matriz aumentada correspondiente al sistema de ecuaciones
entradas=[[2.11,-4.21,0.921,2.01], [4.01,10.2,-1.12,-3.09],[1.09,0.987,0.832,4.21]] #filas corrrespondientes al siste de ecuaciones dal ejemplo

#ciclo iterativo para que el usuario ingrese las entradas de la matriz aumentada

#for k in range(n):
  #lista=[]
  #for d in range(n+1):
    #print("Ingrese el elemnto A",k,d,"de la matriz aumentada")
    #a=float(input(""))
    #lista.append(a)
  #entradas.append(lista)

matrix=array(entradas)#creacion de la matriz aumentada correspondiente al sistema de ecuaciones

print("La matriz aumentada que representa el sistema de ecuaciones es: \n",matrix)

La matriz aumentada que representa el sistema de ecuaciones es: 
 [[ 2.11  -4.21   0.921  2.01 ]
 [ 4.01  10.2   -1.12  -3.09 ]
 [ 1.09   0.987  0.832  4.21 ]]


In [60]:
def intercambio(i,p,matriz,n):#definicion de una funcion para realizar el intercambio de filas dentro del ciclo iterativo
  for x in range(n+1):
    f1=matriz[i][x]#se intercambia la fila i por la fila p
    f2=matriz[p][x]
    matriz[i][x]=f2
    matriz[p][x]=f1
  return matriz




In [61]:
def Calculo_s(matriz,n):#definicion de una funcion para el calculo de si
  matrix3=matriz[0:n,0:n]
  s=[]

  for i in range(n):
    s1=matrix3[i]
    s2=[]
    for j in s1:
      s2.append(abs(j))
    s.append(max(s2))

  return s
print(Calculo_s(matrix,n))


[4.21, 10.2, 1.09]


In [62]:
#Pivoteo Parcial
#Ciclo iterativo
final=matrix #se guarda la matriz aumentada en otro arreglo
s=Calculo_s(matrix,n)
for i in range(n-1):
  matrix=array(final)

  col_i=matrix[i:n,i]#se obtiene la columna i de la matriz
  print(col_i,"coli")
  divi=[]#divisiones de los valores absolutos /si
  for x in range(len(col_i)):
    divi.append(round(abs(col_i[x]/s[x+i]),3))


  ma=max(divi)
  NROW_p_i=divi.index(ma)+i#indice que indica el valor de p
  a_NROW_p_i=col_i[NROW_p_i-i]
  print(s,divi,"s,div")




  if a_NROW_p_i==0:#si el maximo valor absoluto es 0,el sistema no tiene solucion unica
    print("No existe solucion unica")
  else:
    matrix=intercambio(i,NROW_p_i,matrix,n)#llamada de la funcion ,para el intercambio de filas
    s=Calculo_s(matrix,n)
    print("matrix",matrix)

    final=[]#lista vacia para guardar las filas de la matrices  resultantes
    for k in range(i+1):#ciclo para agregar a la lista vacia las fila 0,1,...,i del arreglo "matrix"
        final.append(matrix[k])
    print(final,"final")
    for j in range(i+1,n):#ciclo iterativo para el calculo de los valores de m


        m=round(-matrix[j][i]/matrix[i][i],3)
        print("m",m)
        print("j",j)

        fila1=[]#creacion de una lista vacia
        for f in matrix[i]:#ciclo iterativo para guardar los valoes resultantes del producto de m con cada elemnto de la fila i del arreglo "matrix"
           fila1.append(round(f*m,3))
        print("fi1",fila1)


        sum=list(array(fila1)+array(matrix[j]))#creacion de una lista que alamacena la nueva fila j del arreglo "matrix"
        final.append(sum)#se agrega la nueva fila j del arreglo "matrix " a la lista "final"
    print("La Matriz  es: \n\n",array(final),"\n")#se imprime la matriz resultante

[2.11 4.01 1.09] coli
[4.21, 10.2, 1.09] [0.501, 0.393, 1.0] s,div
matrix [[ 1.09   0.987  0.832  4.21 ]
 [ 4.01  10.2   -1.12  -3.09 ]
 [ 2.11  -4.21   0.921  2.01 ]]
[array([1.09 , 0.987, 0.832, 4.21 ])] final
m -3.679
j 1
fi1 [-4.01, -3.631, -3.061, -15.489]
m -1.936
j 2
fi1 [-2.11, -1.911, -1.611, -8.151]
La Matriz  es: 

 [[  1.09    0.987   0.832   4.21 ]
 [  0.      6.569  -4.181 -18.579]
 [  0.     -6.121  -0.69   -6.141]] 

[ 6.569 -6.121] coli
[1.09, 10.2, 4.21] [0.644, 1.454] s,div
matrix [[  1.09    0.987   0.832   4.21 ]
 [  0.     -6.121  -0.69   -6.141]
 [  0.      6.569  -4.181 -18.579]]
[array([1.09 , 0.987, 0.832, 4.21 ]), array([ 0.   , -6.121, -0.69 , -6.141])] final
m 1.073
j 2
fi1 [0.0, -6.568, -0.74, -6.589]
La Matriz  es: 

 [[ 1.0900e+00  9.8700e-01  8.3200e-01  4.2100e+00]
 [ 0.0000e+00 -6.1210e+00 -6.9000e-01 -6.1410e+00]
 [ 0.0000e+00  1.0000e-03 -4.9210e+00 -2.5168e+01]] 



In [63]:
if final[n-1][n-1]==0:#condicional para verificar que la entrada An,n de la matriz aumentada no sea 0
  print("No existe solucion unica")
else:

  soluciones=zeros(n,dtype=float)#creacion de un arreglo inicializado en 0 para guardar las soluciones del sistema
  soluciones[n-1]=final[n-1][n]/final[n-1][n-1]#calculo de Xn


  def sumatoria(i):#funcion para el calculo de la sumatoria que esta dentro de la formula de Xi
    s=0
    for j in range(i+1,n):
      s+=final[i][j]*soluciones[j]
    return s



  for i in range(n-2,-1,-1):#ciclo iterativo para el calculo de las soluciones Xi
    soluciones[i]=(final[i][n]-sumatoria(i))/final[i][i]


  print("Las soluciones del sistema son : \n")

  for k in range(n):#ciclo iterativo para la impresion de las soluciones
    print("X",k+1,"=",soluciones[k])


Las soluciones del sistema son : 

X 1 = -0.42786864785486456
X 2 = 0.4267372533737679
X 3 = 5.11440764072343


In [64]:
s=Calculo_s(matrix,n)
i=0
col_i=matrix[i:n,i]#se obtiene la columna i de la matriz
divi=[]#divisiones de los valores absolutos /si
for x in range(len(col_i)):
  divi.append(round(abs(col_i[x]/s[x]),5))

print(divi,col_i)
ma=max(divi)
NROW_p_i=divi.index(ma)+i#indice que indica el valor de p
a_NROW_p_i=col_i[NROW_p_i-i]
print(ma,NROW_p_i,a_NROW_p_i)

[1.0, 0.0, 0.0] [1.09 0.   0.  ]
1.0 0 1.09
