<a href="https://colab.research.google.com/github/Sandoval-Martinez-Jacquelin/Metodos-1/blob/main/Pivoteo%20Parcial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PIVOTEO PARCIAL**

In [88]:
import numpy as np
from numpy import array

from numpy import zeros

from math import *

In [89]:
#Ingreso del numero de incognitas y ecuaciones del sistema
n=4#int(input("Ingrese el numero de Incognitas y numero de ecuaciones= "))
#entradas=[] #Lista vacia para alamcenar las filas de la matriz aumentada correspondiente al sistema de ecuaciones
entradas=[[1., -1., 2.,-1.,-8.], [2.,-2., 3.,-3.,-20.],[1.,1.,1.,0.,-2.], [1., -1., 4.,3.,4.]]#filas corrrespondientes al siste de ecuaciones dal ejemplo

#ciclo iterativo para que el usuario ingrese las entradas de la matriz aumentada

#for k in range(n):
  #lista=[]
  #for d in range(n+1):
    #print("Ingrese el elemnto A",k,d,"de la matriz aumentada")
    #a=float(input(""))
    #lista.append(a)
  #entradas.append(lista)

matrix=array(entradas,dtype=float)#creacion de la matriz aumentada correspondiente al sistema de ecuaciones

print("La matriz aumentada que representa el sistema de ecuaciones es: \n",matrix)

La matriz aumentada que representa el sistema de ecuaciones es: 
 [[  1.  -1.   2.  -1.  -8.]
 [  2.  -2.   3.  -3. -20.]
 [  1.   1.   1.   0.  -2.]
 [  1.  -1.   4.   3.   4.]]


In [90]:
final=matrix

NROW=zeros(n)
for i in range(n):
  NROW[i]=i






In [91]:
print(final)

[[  1.  -1.   2.  -1.  -8.]
 [  2.  -2.   3.  -3. -20.]
 [  1.   1.   1.   0.  -2.]
 [  1.  -1.   4.   3.   4.]]


In [93]:
i=1
col0=final[:,i]
ab=zeros(n)
for j in range(i,n):
  b=col0[j]
  ab[j]=b
print(col0,"col0")
print("ab",ab)

[-1. -2.  1. -1.] col0
ab [ 0. -2.  1. -1.]
