<a href="https://colab.research.google.com/github/Sandoval-Martinez-Jacquelin/Metodos-1/blob/main/Pivoteo%20Parcial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PIVOTEO PARCIAL**

In [91]:
import numpy as np
from numpy import array

from numpy import zeros

from math import *

In [92]:
#Ingreso del numero de incognitas y ecuaciones del sistema
n=2#int(input("Ingrese el numero de Incognitas y numero de ecuaciones= "))
#entradas=[] #Lista vacia para alamcenar las filas de la matriz aumentada correspondiente al sistema de ecuaciones
entradas=[[0.003000,59.14,59.17], [5.291,-6.130,46.78]] #filas corrrespondientes al siste de ecuaciones dal ejemplo

#ciclo iterativo para que el usuario ingrese las entradas de la matriz aumentada

#for k in range(n):
  #lista=[]
  #for d in range(n+1):
    #print("Ingrese el elemnto A",k,d,"de la matriz aumentada")
    #a=float(input(""))
    #lista.append(a)
  #entradas.append(lista)

matrix=array(entradas,dtype=float)#creacion de la matriz aumentada correspondiente al sistema de ecuaciones

print("La matriz aumentada que representa el sistema de ecuaciones es: \n",matrix)

La matriz aumentada que representa el sistema de ecuaciones es: 
 [[ 3.000e-03  5.914e+01  5.917e+01]
 [ 5.291e+00 -6.130e+00  4.678e+01]]


In [93]:
i=0
matrix2=matrix
col0=list(matrix[:,i])#se obtiene la columna i
a_NROW_J_i=list(zeros(n))#arreglo para guardar los valores absolutos de la columna i
for j in range(i,n):#ciclo para añadir los valores absolutos de la columna i,a partir del elemnto i de la columna

  a_NROW_J_i[j]=abs(col0[j])#valores absolutos de la columna i,a partir del elemnto i de la columna

a_NROW_p_i=max(a_NROW_J_i)#se encuentra el maximo absoluto del arreglo con valores absolutos
NROW_p_i=a_NROW_J_i.index(a_NROW_p_i)#se encuentra el indice del maximo valor absoluto de la columna i
print(col0,"col0")
print("ab",a_NROW_J_i)
print(a_NROW_p_i,NROW_p_i,"MAXIMO,INDICE")

if a_NROW_p_i==0:
  print("No existe solucion unica")
else:
  print(NROW_p_i,"indice del valor maximo")
  print(i,"valor de i")
  NCOPY1=matrix[i]
  NCOPY2=matrix[NROW_p_i]
  print("fila i",NCOPY1)
  print("fila 2",NCOPY2)
  print(matrix,"FILA P")
  matrix2[i]=NCOPY2
  matrix2[NROW_p_i]=NCOPY1
  print(matrix2)

[0.003, 5.291] col0
ab [0.003, 5.291]
5.291 1 MAXIMO,INDICE
1 indice del valor maximo
0 valor de i
fila i [3.000e-03 5.914e+01 5.917e+01]
fila 2 [ 5.291 -6.13  46.78 ]
[[ 3.000e-03  5.914e+01  5.917e+01]
 [ 5.291e+00 -6.130e+00  4.678e+01]] FILA P
[[ 5.291 -6.13  46.78 ]
 [ 5.291 -6.13  46.78 ]]


In [8]:
print("Las matrices equivalentes son: \n\n")
final=entradas
#Ciclo iterativo
#Eliminacion Gaussiana con sustitucion hacia atras

for i in range(n):
  #creacion de arreglos para almacenar las matrices equivalentes resultantes
  entradas2=array(final)
  entradas=array(final)
  matrix=array(entradas2)


  col0=list(entradas2[: , i])#se obtiene la columna i del arreglo "entradas2"

  cero=[0.,0.,0.,0.]
  if col0 == cero:#si todas las entradas de la columna i son 0 ,el sistema no tiene solucion unica
    print("No existe solucion unica")
  else:
    col=col0[i:]#se obtienen los elemntos de la lista "col0" desde el subindice i hasta el ultimo elemnto y se guardan en la lista "col"

    for k in col:#ciclo para recorrer los elementos de la lista "col"
      if k!=0:
        a=k#el primer elemnto diferente de 0 ,de la lista "col" se guarda en la variable "a"
        break
    p=col.index(a)+i #se obtiene el subindice del valor de "a" ,dentro de  "col0" y se almacena en la variable "p"

    if p!=i:#si el valor de p e i son distintos,se intercambian las filas p e i del arreglo "entradas2"
      b=entradas[i]
      c=entradas[p]
      entradas2[i]=c
      entradas2[p]=b





    final=[]#lista vacia para guardar las filas de la matrices equivbalentes resultantes de las operaciones elemntales
    for k in range(i+1):#ciclo para agregar a la lista vacia las fila 0,1,...,i del arreglo "entradas2"
      final.append(entradas2[k])

    for j in range(i+1,n):#ciclo iterativo para el calculo de los valores de m

      m=-entradas2[j][i]/entradas2[i][i]


      fila1=[]#creacion de una lista vacia
      for f in entradas2[i]:#ciclo iterativo para guardar los valoes resultantes del producto de m con cada elemnto de la fila i del arreglo "entradas2"
         fila1.append(f*m)


      sum=list(array(fila1)+array(entradas2[j]))#creacion de una lista que alamacena la nueva fila j del arreglo "entradas2"
      final.append(sum)#se agrega la nueva fila j del arreglo "entradas2 " a la lista "final"
  print("La Matriz equivalente es: \n\n",array(final),"\n")#se imprime la matriz equivalente ,resultado de las operaciones elemntales



Las matrices equivalentes son: 


La Matriz equivalente es: 

 [[ 3.00000000e-03  5.91400000e+01  5.91700000e+01]
 [ 0.00000000e+00 -1.04309377e+05 -1.04309377e+05]] 

La Matriz equivalente es: 

 [[ 3.00000000e-03  5.91400000e+01  5.91700000e+01]
 [ 0.00000000e+00 -1.04309377e+05 -1.04309377e+05]] 

