<a href="https://colab.research.google.com/github/Sandoval-Martinez-Jacquelin/Metodos-1/blob/main/Pivoteo%20Parcial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PIVOTEO PARCIAL**

In [42]:
import numpy as np
from numpy import array

from numpy import zeros

from math import *

In [43]:
#Ingreso del numero de incognitas y ecuaciones del sistema
n=4#int(input("Ingrese el numero de Incognitas y numero de ecuaciones= "))
#entradas=[] #Lista vacia para alamcenar las filas de la matriz aumentada correspondiente al sistema de ecuaciones
entradas=[[1., -1., 2.,-1.,-8.], [2.,-2., 3.,-3.,-20.],[1.,1.,1.,0.,-2.], [1., -1., 4.,3.,4.]]#filas corrrespondientes al siste de ecuaciones dal ejemplo

#ciclo iterativo para que el usuario ingrese las entradas de la matriz aumentada

#for k in range(n):
  #lista=[]
  #for d in range(n+1):
    #print("Ingrese el elemnto A",k,d,"de la matriz aumentada")
    #a=float(input(""))
    #lista.append(a)
  #entradas.append(lista)

matrix=array(entradas,dtype=float)#creacion de la matriz aumentada correspondiente al sistema de ecuaciones

print("La matriz aumentada que representa el sistema de ecuaciones es: \n",matrix)

La matriz aumentada que representa el sistema de ecuaciones es: 
 [[  1.  -1.   2.  -1.  -8.]
 [  2.  -2.   3.  -3. -20.]
 [  1.   1.   1.   0.  -2.]
 [  1.  -1.   4.   3.   4.]]


In [44]:
final=matrix
final2=matrix

NROW=zeros(n)
for i in range(n):
  NROW[i]=i





In [45]:
i=0

col0=list(final[:,i])
ab=list(zeros(n))
for j in range(i,n):

  ab[j]=abs(col0[j])

ma=max(ab)
NROW_p=ab.index(ma)
print(col0,"col0")
print("ab",ab)
print(ma,NROW_p,"MAXIMO,INDICE")



if final[NROW_p][i]==0:
  print("No existe solucion unica")
else:
  NCOPY1=final2[i]
  NCOPY2=final2[NROW_p]
  final[i]=NCOPY1
  final[NROW_p]=NCOPY2




  print(final,"modificacon fila")



[1.0, 2.0, 1.0, 1.0] col0
ab [1.0, 2.0, 1.0, 1.0]
2.0 1 MAXIMO,INDICE
[[  1.  -1.   2.  -1.  -8.]
 [  2.  -2.   3.  -3. -20.]
 [  1.   1.   1.   0.  -2.]
 [  1.  -1.   4.   3.   4.]] modificacon fila
