<a href="https://colab.research.google.com/github/Sandoval-Martinez-Jacquelin/Metodos-1/blob/main/Pivoteo%20Parcial%20Escalonado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PIVOTEO PARCIAL ESCALONADO**

In [ ]:
import numpy as np
from numpy import array

from numpy import zeros

from math import *

In [ ]:
#Ingreso del numero de incognitas y ecuaciones del sistema
n=2#int(input("Ingrese el numero de Incognitas y numero de ecuaciones= "))
#entradas=[] #Lista vacia para alamcenar las filas de la matriz aumentada correspondiente al sistema de ecuaciones
entradas=[[0.003,59.14,59.17], [5.291,-6.130,46.78]] #filas corrrespondientes al siste de ecuaciones dal ejemplo

#ciclo iterativo para que el usuario ingrese las entradas de la matriz aumentada

#for k in range(n):
  #lista=[]
  #for d in range(n+1):
    #print("Ingrese el elemnto A",k,d,"de la matriz aumentada")
    #a=float(input(""))
    #lista.append(a)
  #entradas.append(lista)

matrix=array(entradas)#creacion de la matriz aumentada correspondiente al sistema de ecuaciones

print("La matriz aumentada que representa el sistema de ecuaciones es: \n",matrix)

La matriz aumentada que representa el sistema de ecuaciones es: 
 [[ 3.000e-03  5.914e+01  5.917e+01]
 [ 5.291e+00 -6.130e+00  4.678e+01]]


In [ ]:
def intercambio(i,p,matriz,n):#definicion de una funcion para realizar el intercambio de filas dentro del ciclo iterativo
  for x in range(n+1):
    f1=matriz[i][x]#se intercambia la fila i por la fila p
    f2=matriz[p][x]
    matriz[i][x]=f2
    matriz[p][x]=f1
  return matriz




In [ ]:
#Pivoteo Parcial
#Ciclo iterativo
final=matrix #se guarda la matriz aumentada en otro arreglo
for i in range(n-1):
  matrix=array(final)
  col0=list(matrix[:,i])#se obtiene la columna i de la matriz aumentada del sistema de ecuaciones
  a_NROW_J_i=list(zeros(n))#arreglo para guardar los valores absolutos de la columna i
  for j in range(i,n):#ciclo para añadir los valores absolutos de la columna i

    a_NROW_J_i[j]=abs(col0[j])#valores absolutos de la columna i,a partir del elemnto i de la columna

  a_NROW_p_i=max(a_NROW_J_i)#se encuentra el maximo absoluto del arreglo que contiene los  valores absolutos
  NROW_p_i=a_NROW_J_i.index(a_NROW_p_i)#se encuentra el indice del maximo valor absoluto de la columna i


  if a_NROW_p_i==0:#si el maximo valor absoluto es 0,el sistema no tiene solucion unica
    print("No existe solucion unica")
  else:
    matrix=intercambio(i,NROW_p_i,matrix,n)#llamada de la funcion ,para el intercambio de filas

    final=[]#lista vacia para guardar las filas de la matrices  resultantes
    for k in range(i+1):#ciclo para agregar a la lista vacia las fila 0,1,...,i del arreglo "matrix"
        final.append(matrix[k])

    for j in range(i+1,n):#ciclo iterativo para el calculo de los valores de m

        m=-matrix[j][i]/matrix[i][i]


        fila1=[]#creacion de una lista vacia
        for f in matrix[i]:#ciclo iterativo para guardar los valoes resultantes del producto de m con cada elemnto de la fila i del arreglo "matrix"
           fila1.append(round(f*m,7))


        sum=list(array(fila1)+array(matrix[j]))#creacion de una lista que alamacena la nueva fila j del arreglo "matrix"
        final.append(sum)#se agrega la nueva fila j del arreglo "matrix " a la lista "final"
    print("La Matriz  es: \n\n",array(final),"\n")#se imprime la matriz resultante



La Matriz  es: 

 [[ 5.291     -6.13      46.78     ]
 [ 0.        59.1434757 59.1434757]] 



In [ ]:
if final[n-1][n-1]==0:#condicional para verificar que la entrada An,n de la matriz aumentada no sea 0
  print("No existe solucion unica")
else:

  soluciones=zeros(n,dtype=float)#creacion de un arreglo inicializado en 0 para guardar las soluciones del sistema
  soluciones[n-1]=final[n-1][n]/final[n-1][n-1]#calculo de Xn


  def sumatoria(i):#funcion para el calculo de la sumatoria que esta dentro de la formula de Xi
    s=0
    for j in range(i+1,n):
      s+=final[i][j]*soluciones[j]
    return s



  for i in range(n-2,-1,-1):#ciclo iterativo para el calculo de las soluciones Xi
    soluciones[i]=(final[i][n]-sumatoria(i))/final[i][i]


  print("Las soluciones del sistema son : \n")

  for k in range(n):#ciclo iterativo para la impresion de las soluciones
    print("X",k+1,"=",soluciones[k])


Las soluciones del sistema son : 

X 1 = 10.0
X 2 = 1.0
