<a href="https://colab.research.google.com/github/Sandoval-Martinez-Jacquelin/Metodos-1/blob/main/Tutorial_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **TUTORIAL DE NUMPY**

NumPy es una librería de Python especializada en eL cálculo numérico y el análisis de datos, especialmente para un gran volumen de datos.

Incorpora una nueva clase de objetos llamados arrays que permite representar colecciones de datos de un mismo tipo en varias dimensiones, y funciones muy eficientes para su manipulación.

Caracteristicas de los Arreglos.


*   Son del mismo tipo de dato
*   Tienen una posicion numerica ,la cual inicia en 0
*   Una vez creado el arreglo no se puede modificar su tamaño






In [77]:
#Para usar NumPy debemos importar el módulo numpy, típicamente usando el alias np
import numpy as np #Importa todo el paquete numpy y se usa de la  #siguiente forma:  np.array(A)
from numpy import array #Importa la función array del paquete numpy
from numpy import *  #Importa todas las funciones dentro del paquete numpy
#Los arreglos pueden ser de tipo flotante,entero,complejo o cadena


**Creacion de Arreglos.**

In [78]:
#Apartir de Listas.
A=[1, 3, 5, 7, 9, 2, 4, 6, 8]#lista
B=array(A)#Creamos el arreglo "B" con los elementos de la lista A,el arreglo es de tipo entero


print("Lista",A)
print("Arreglo",B)

C=array([[1, 3, 5], [7., 9., 2.], [4, 6, 8]])#La segunda lista contiene datos flotantes

print("Arreglo de tipo flotante\n",C)

Lista [1, 3, 5, 7, 9, 2, 4, 6, 8]
Arreglo [1 3 5 7 9 2 4 6 8]
Arreglo de tipo flotante
 [[1. 3. 5.]
 [7. 9. 2.]
 [4. 6. 8.]]


In [79]:
#Arreglos con arange
#Crea un arreglo con numeros de coma flotante.Podemos crear un arreglo de 3 distintas formas
#1.arange(fin-1)
a=arange(10.0)
print("arange(fin-1),parametro flotante\n",a,"\n")
#2 arange(inicio, fin-1)
a=arange(13,18)
print("arange(inicio,fin-1),parametro entero\n",a,"\n")
#3.arange(inicio, fin-1, paso)
a=arange(4,20,2)
print("arange(inicio,fin-1,paso),parametro entero\n",a,"\n")

arange(fin-1),parametro flotante
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] 

arange(inicio,fin-1),parametro entero
 [13 14 15 16 17] 

arange(inicio,fin-1,paso),parametro entero
 [ 4  6  8 10 12 14 16 18] 



**Arreglos inicializados en cero o uno**

In [80]:
#ARREGLOS INICIALIZADOS EN CERO
#importamos el modulo numpy
from numpy import zeros #inicializa lo arreglos en 0
from numpy import ones #inicializa lo arreglos en 1


G=zeros(3,dtype=int)#crea arreglo de tipo entero
H=zeros(3,dtype=float)#crea arreglo de tipo flotante
J=zeros(3,dtype=complex)#crea arreglo de tipo complejo
K=zeros(3,dtype=str)#crea arreglo de tipo cadena
print("Arreglo de tipo entero",G)
print("Arreglo de tipo flotante",H)
print("Arreglo de tipo complejo",J)
print("Arreglo de tipo cadena",K)

#Para arreglos de dimension 2 o supeior ,las dimensiones del array son tuplas
dimen=(2,3)
M=zeros(dimen,dtype=int)
print("Array de dimension 2x3 \n",M)


Arreglo de tipo entero [0 0 0]
Arreglo de tipo flotante [0. 0. 0.]
Arreglo de tipo complejo [0.+0.j 0.+0.j 0.+0.j]
Arreglo de tipo cadena ['' '' '']
Array de dimension 2x3 
 [[0 0 0]
 [0 0 0]]


In [81]:
#ARREGLOS INICIALIZADOS EN UNO
#importamos el modulo numpy
from numpy import ones #inicializa lo arreglos en 1
G=ones(3,dtype=int)#crea arreglo de tipo entero
H=ones(3,dtype=float)#crea arreglo de tipo flotante
J=ones(3,dtype=complex)#crea arreglo de tipo complejo
K=ones(3,dtype=str)#crea arreglo de tipo cadena
print("Arreglo de tipo entero",G)
print("Arreglo de tipo flotante",H)
print("Arreglo de tipo complejo",J)
print("Arreglo de tipo cadena",K)
#Para arreglos de dimension 2 o supeior ,las dimensiones del array son tuplas
dimen=(2,3)
M=ones(dimen,dtype=int)
print("Array de dimension 2x3 \n",M)


Arreglo de tipo entero [1 1 1]
Arreglo de tipo flotante [1. 1. 1.]
Arreglo de tipo complejo [1.+0.j 1.+0.j 1.+0.j]
Arreglo de tipo cadena ['1' '1' '1']
Array de dimension 2x3 
 [[1 1 1]
 [1 1 1]]


In [82]:
#inicialización con todos los valores a un valor predeterminado
# El tipo de dato coincide con el del dato de inicialización
a=full(10, 3)#arreglo con 10 numeros 3
print(a)

[3 3 3 3 3 3 3 3 3 3]


**Arreglos con Linspace**

In [83]:
#crea una secuencia de valores equidistantes entre dos valores límite.Sus argumentos son:inicio,fin ,numero de elementos
j=linspace(2,15,13)#arreglo con 13 valores equidistantes ,se empieza en 2 y acaba en 15
print("Arreglo con 13 valores equidistantes ,se empieza en 2 y acaba en 15\n",j)
#NOTA:"SE GENERAN MENOS DECIMALES CUANDO EL NUMERO DE ELEMENTOS ES IMPAR"

Arreglo con 13 valores equidistantes ,se empieza en 2 y acaba en 15
 [ 2.          3.08333333  4.16666667  5.25        6.33333333  7.41666667
  8.5         9.58333333 10.66666667 11.75       12.83333333 13.91666667
 15.        ]


**inicialización de valores aleatorios enteros pertenecientes a un rango de valores**

In [84]:
a=random.randint(-9, 10, (5, 5))#Matriz 5x5 de enteros aleatorios en el intervalo abierto [-9, 10)
print(a)

[[-9  2 -3  2 -9]
 [-6 -9 -5  8  9]
 [ 2  4  8  9 -9]
 [-4 -3  4 -6 -6]
 [ 7 -6 -9  1 -6]]


**Modificar los elementos de un arreglo.**

In [85]:
from numpy import zeros #inicializa lo arreglos en 0
a=zeros(10,dtype=int)#creacion del arreglo inicicalizado en 0
print("Arreglo inicializado en 0\n",a)
#Modificacion del arreglo a
for x in range(len(a)):#creacion de un bucle para la modificacion del arreglo
  a[x]=x+1 #modifica el dato del arreglo de la posicion x y le asigna el nuevo valor = x+1

print("Arreglo modificado\n",a)

Arreglo inicializado en 0
 [0 0 0 0 0 0 0 0 0 0]
Arreglo modificado
 [ 1  2  3  4  5  6  7  8  9 10]


**Indexado**

In [86]:
#Para arreglos unidimensionales
v = np.random.randint(-9, 10, 5)#Arreglo de enteros aleatorios en el intervalo abierto [-9, 10)
print(v)
print("Elemento 0 del arreglo V es ",v[0],"\n")

#Indexado para Arreglos multidimensionales
#accedemos individualmente a los elementos, que son valores escalares, separando los índices por comas
M = np.random.randint(-9, 10, (5, 3))#Matriz 5x3 de enteros aleatorios en el intervalo abierto [-9, 10)
print("La matriz M es \n",M)
print("El escalar de la fila 1 ,columna 2 es= ",  M[1, 2])#RECORDEMOS QUE LA PRIMERA POSICION DE UN ELEMNTO TIENE EL INDICE 0

[6 5 2 7 3]
Elemento 0 del arreglo V es  6 

La matriz M es 
 [[-6  9 -5]
 [-6 -8  7]
 [-4  0  8]
 [ 6 -3  0]
 [ 6  1  9]]
El escalar de la fila 1 ,columna 2 es=  7


In [87]:
#Si queremos acceder, por ejemplo, a toda una fila de una matriz de dos dimensiones, indicamos simplemente el índice de la fila
print("fila 1",M[1],"\n")

#Lo mismo se puede conseguir usando la notación :
print("fila 2",M[2, :],"\n") #fila 2

# acceder a toda una columna
print("Columna 1",M[:, 1],"\n")

#Las asignaciones a elementos individuales siguen las pautas normales:
M[1, 2] = 150
print("Matriz M \n",M,"\n")

#También podemos asignar un valor a todos los elementos de una fila o columna:
M[2, :] = 800
M[:, 1] = -20
print("Matriz M \n",M)

fila 1 [-6 -8  7] 

fila 2 [-4  0  8] 

Columna 1 [ 9 -8  0 -3  1] 

Matriz M 
 [[ -6   9  -5]
 [ -6  -8 150]
 [ -4   0   8]
 [  6  -3   0]
 [  6   1   9]] 

Matriz M 
 [[ -6 -20  -5]
 [ -6 -20 150]
 [800 -20 800]
 [  6 -20   0]
 [  6 -20   9]]


**Atributos de los array**

In [88]:
#SHAPE
#Se obtienen las dimensiones de un array y devuelve una tuplea
M = ones((2, 3), dtype=float)
print(M.shape)

#SIZE
#accede al número de elementos
print(M.ndim)

#NDIM
#El número de dimensiones se almacena en el atributo ndim
print(M.ndim)

#Se puede obtener también consultando la longitud de la tupla shape
print(len(M.shape))

(2, 3)
2
2
2


**Operaciones con arreglos**

In [89]:
#Las operaciones de un escalar y un arreglo se realizan con el escalar operando con todos los elementos del arreglo
a=array([1,2,3,4,5])#creacion del arreglo
f=5
c=a+f
e=a*f
h=a-f
p=a/f
print("Suma ",c,"\nProducto ",e,"\nDiferencia ",h,"\nCociente ",p)


Suma  [ 6  7  8  9 10] 
Producto  [ 5 10 15 20 25] 
Diferencia  [-4 -3 -2 -1  0] 
Cociente  [0.2 0.4 0.6 0.8 1. ]


In [90]:
#Las operaciones entre arreglos se realizan elemento a elemnto
a=array([1,2,3,4,5])
b=array([6,7,8,9,10])
c=a+b
e=a*b
h=a-b
p=a/b
print("Suma ",c,"\nProducto ",e,"\nDiferencia ",h,"\nCociente ",p)


Suma  [ 7  9 11 13 15] 
Producto  [ 6 14 24 36 50] 
Diferencia  [-5 -5 -5 -5 -5] 
Cociente  [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


**Suma y producto de los elementos, suma y producto acumulativos**

In [91]:
M=array([[1,2,3],[4,5,6],[7,8,9]])
print(M,"\n")

#suma de los elemntos de M
print("Suma= ",sum(M))
print("\nProducto ",prod(M))#multiplica todos los elemntos de M
# Suma acumulativa. Recorre por filas.
print("Suma acumulativa ",cumsum(M))
# Producto acumulativo. Recorre por filas.
print("\nProducto acumulativo ",cumprod(M))

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

Suma=  45

Producto  362880
Suma acumulativa  [ 1  3  6 10 15 21 28 36 45]

Producto acumulativo  [     1      2      6     24    120    720   5040  40320 362880]


**Combinando matrices**

In [92]:
#Concatenar
v1 = np.array([1, 2, 3])#creacion de arreglos
v2 = np.array([4, 5, 6])
v3 = np.array([7, 8, 9])

M = np.concatenate((v1, v2, v3))
print(M)

[1 2 3 4 5 6 7 8 9]


In [93]:
#Apilar, horizontal y verticalmente
M = np.vstack((v1, v2, v3))#apila verticalemnte
print("Apilacion vertical\n" ,M)
M = np.hstack((v1, v2, v3))  # apila horizontalmente
print("Apilacion horizontal\n" ,M)

Apilacion vertical
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Apilacion horizontal
 [1 2 3 4 5 6 7 8 9]


**Iterando con bucles de arreglos**



In [94]:
#Iteracion de arreglos unidimensionales
v = arange(10) #creacion del arreglo ,contiene numeros del 0-9
print("arreglo ",v)
for x in v:
    print(x) #con el bucle se accede a cada elemento del arreglo v

arreglo  [0 1 2 3 4 5 6 7 8 9]
0
1
2
3
4
5
6
7
8
9


In [95]:
#Iteracion de matrices
M = array([[2, 1, 7], [5, 2, 9], [2, 8, 5]])
print("Matriz M =\n",M)
#Accedemos a los elemntos de M a traves del bucle
print("\nLos elemntos de M son \n")
for fila in M:  # fila es una fila de M
    for x in fila:
        print(x, end=' ')#imprime cada elemnto de M
    print()

Matriz M =
 [[2 1 7]
 [5 2 9]
 [2 8 5]]

Los elemntos de M son 

2 1 7 
5 2 9 
2 8 5 
