<a href="https://colab.research.google.com/github/Sandoval-Martinez-Jacquelin/Metodos-1/blob/main/Tutorial_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **TUTORIAL DE NUMPY**

NumPy es una librería de Python especializada en eL cálculo numérico y el análisis de datos, especialmente para un gran volumen de datos.

Incorpora una nueva clase de objetos llamados arrays que permite representar colecciones de datos de un mismo tipo en varias dimensiones, y funciones muy eficientes para su manipulación.

In [1]:
#Para usar NumPy debemos importar el módulo numpy, típicamente usando el alias np
import numpy as np #Importa todo el paquete numpy y se usa de la  #siguiente forma:  np.array(A)
from numpy import array #Importa la función array del paquete numpy
from numpy import *  #Importa todas las funciones dentro del paquete numpy



**Creacion de Arreglos.**

In [9]:
#Apartir de Listas.
A=[1, 3, 5, 7, 9, 2, 4, 6, 8]#lista
B=array(A)#Creamos el arreglo "B" con los elementos de la lista A,el arreglo es de tipo entero


print("Lista",A)
print("Arreglo",B)

C=array([[1, 3, 5], [7., 9., 2.], [4, 6, 8]])#La segunda lista contiene datos flotantes

print("Arreglo de tipo flotante\n",C)

Lista [1, 3, 5, 7, 9, 2, 4, 6, 8]
Arreglo [1 3 5 7 9 2 4 6 8]
Arreglo de tipo flotante
 [[1. 3. 5.]
 [7. 9. 2.]
 [4. 6. 8.]]


In [15]:
#Arreglos con arange
#Crea un arreglo con numeros de coma flotante.Podemos crear un arreglo de 3 distintas formas
#1.arange(fin-1)
a=arange(10.0)
print("arange(fin-1),parametro flotante\n",a,"\n")
#2 arange(inicio, fin-1)
a=arange(13,18)
print("arange(inicio,fin-1),parametro entero\n",a,"\n")
#3.arange(inicio, fin-1, paso)
a=arange(4,20,2)
print("arange(inicio,fin-1,paso),parametro entero\n",a,"\n")

arange(fin-1),parametro flotante
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] 

arange(inicio,fin-1),parametro entero
 [13 14 15 16 17] 

arange(inicio,fin-1,paso),parametro entero
 [ 4  6  8 10 12 14 16 18] 

